// Code generated by protoc-gen-gogo.
// source: rpc_msg.proto
// DO NOT EDIT!

/*
	Package rpc is a generated protocol buffer package.

	It is generated from these files:
		rpc_msg.proto

	It has these top-level messages:
		RPCValue
		RPCHandShake
		RPCMethodCall
		RPCMethodReturn
*/
package rpc

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RPC_MSGID int32

const (
	RPC_MSGID_HANDSHAKE RPC_MSGID = -256
	RPC_MSGID_CALL      RPC_MSGID = -512
	RPC_MSGID_RETURN    RPC_MSGID = -514
)

var RPC_MSGID_name = map[int32]string{
	-256: "HANDSHAKE",
	-512: "CALL",
	-514: "RETURN",
}
var RPC_MSGID_value = map[string]int32{
	"HANDSHAKE": -256,
	"CALL":      -512,
	"RETURN":    -514,
}

func (x RPC_MSGID) Enum() *RPC_MSGID {
	p := new(RPC_MSGID)
	*p = x
	return p
}
func (x RPC_MSGID) String() string {
	return proto.EnumName(RPC_MSGID_name, int32(x))
}
func (x *RPC_MSGID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RPC_MSGID_value, data, "RPC_MSGID")
	if err != nil {
		return err
	}
	*x = RPC_MSGID(value)
	return nil
}
func (RPC_MSGID) EnumDescriptor() ([]byte, []int) { return fileDescriptorRpcMsg, []int{0} }

type RPCValue struct {
	Kind int32     `protobuf:"varint,1,req,name=kind" json:"kind"`
	I32  int32     `protobuf:"varint,2,req,name=i32" json:"i32"`
	I64  int64     `protobuf:"varint,3,req,name=i64" json:"i64"`
	U32  uint32    `protobuf:"varint,4,req,name=u32" json:"u32"`
	U64  uint64    `protobuf:"varint,5,req,name=u64" json:"u64"`
	F32  float32   `protobuf:"fixed32,6,req,name=f32" json:"f32"`
	F64  float64   `protobuf:"fixed64,7,req,name=f64" json:"f64"`
	B    bool      `protobuf:"varint,8,req,name=b" json:"b"`
	S    string    `protobuf:"bytes,9,req,name=s" json:"s"`
	I32A []int32   `protobuf:"varint,10,rep,name=i32a" json:"i32a,omitempty"`
	I64A []int64   `protobuf:"varint,11,rep,name=i64a" json:"i64a,omitempty"`
	U32A []uint32  `protobuf:"varint,12,rep,name=u32a" json:"u32a,omitempty"`
	U64A []uint64  `protobuf:"varint,13,rep,name=u64a" json:"u64a,omitempty"`
	F32A []float32 `protobuf:"fixed32,14,rep,name=f32a" json:"f32a,omitempty"`
	F64A []float64 `protobuf:"fixed64,15,rep,name=f64a" json:"f64a,omitempty"`
	Ba   []bool    `protobuf:"varint,16,rep,name=ba" json:"ba,omitempty"`
	Sa   []string  `protobuf:"bytes,17,rep,name=sa" json:"sa,omitempty"`
}

func (m *RPCValue) Reset()                    { *m = RPCValue{} }
func (m *RPCValue) String() string            { return proto.CompactTextString(m) }
func (*RPCValue) ProtoMessage()               {}
func (*RPCValue) Descriptor() ([]byte, []int) { return fileDescriptorRpcMsg, []int{0} }

func (m *RPCValue) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *RPCValue) GetI32() int32 {
	if m != nil {
		return m.I32
	}
	return 0
}

func (m *RPCValue) GetI64() int64 {
	if m != nil {
		return m.I64
	}
	return 0
}

func (m *RPCValue) GetU32() uint32 {
	if m != nil {
		return m.U32
	}
	return 0
}

func (m *RPCValue) GetU64() uint64 {
	if m != nil {
		return m.U64
	}
	return 0
}

func (m *RPCValue) GetF32() float32 {
	if m != nil {
		return m.F32
	}
	return 0
}

func (m *RPCValue) GetF64() float64 {
	if m != nil {
		return m.F64
	}
	return 0
}

func (m *RPCValue) GetB() bool {
	if m != nil {
		return m.B
	}
	return false
}

func (m *RPCValue) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *RPCValue) GetI32A() []int32 {
	if m != nil {
		return m.I32A
	}
	return nil
}

func (m *RPCValue) GetI64A() []int64 {
	if m != nil {
		return m.I64A
	}
	return nil
}

func (m *RPCValue) GetU32A() []uint32 {
	if m != nil {
		return m.U32A
	}
	return nil
}

func (m *RPCValue) GetU64A() []uint64 {
	if m != nil {
		return m.U64A
	}
	return nil
}

func (m *RPCValue) GetF32A() []float32 {
	if m != nil {
		return m.F32A
	}
	return nil
}

func (m *RPCValue) GetF64A() []float64 {
	if m != nil {
		return m.F64A
	}
	return nil
}

func (m *RPCValue) GetBa() []bool {
	if m != nil {
		return m.Ba
	}
	return nil
}

func (m *RPCValue) GetSa() []string {
	if m != nil {
		return m.Sa
	}
	return nil
}

type RPCHandShake struct {
	EndName      string `protobuf:"bytes,1,req,name=endName" json:"endName"`
	EndModelName string `protobuf:"bytes,2,req,name=endModelName" json:"endModelName"`
}

func (m *RPCHandShake) Reset()                    { *m = RPCHandShake{} }
func (m *RPCHandShake) String() string            { return proto.CompactTextString(m) }
func (*RPCHandShake) ProtoMessage()               {}
func (*RPCHandShake) Descriptor() ([]byte, []int) { return fileDescriptorRpcMsg, []int{1} }

func (m *RPCHandShake) GetEndName() string {
	if m != nil {
		return m.EndName
	}
	return ""
}

func (m *RPCHandShake) GetEndModelName() string {
	if m != nil {
		return m.EndModelName
	}
	return ""
}

type RPCMethodCall struct {
	CallSeq uint32               `protobuf:"varint,1,req,name=call_seq,json=callSeq" json:"call_seq"`
	Method  string               `protobuf:"bytes,2,req,name=method" json:"method"`
	Args    map[string]*RPCValue `protobuf:"bytes,3,rep,name=args" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Caller  string               `protobuf:"bytes,4,req,name=caller" json:"caller"`
}

func (m *RPCMethodCall) Reset()                    { *m = RPCMethodCall{} }
func (m *RPCMethodCall) String() string            { return proto.CompactTextString(m) }
func (*RPCMethodCall) ProtoMessage()               {}
func (*RPCMethodCall) Descriptor() ([]byte, []int) { return fileDescriptorRpcMsg, []int{2} }

func (m *RPCMethodCall) GetCallSeq() uint32 {
	if m != nil {
		return m.CallSeq
	}
	return 0
}

func (m *RPCMethodCall) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RPCMethodCall) GetArgs() map[string]*RPCValue {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *RPCMethodCall) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

type RPCMethodReturn struct {
	CallSeq uint32               `protobuf:"varint,1,req,name=call_seq,json=callSeq" json:"call_seq"`
	Method  string               `protobuf:"bytes,2,req,name=method" json:"method"`
	Returns map[string]*RPCValue `protobuf:"bytes,3,rep,name=returns" json:"returns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RPCMethodReturn) Reset()                    { *m = RPCMethodReturn{} }
func (m *RPCMethodReturn) String() string            { return proto.CompactTextString(m) }
func (*RPCMethodReturn) ProtoMessage()               {}
func (*RPCMethodReturn) Descriptor() ([]byte, []int) { return fileDescriptorRpcMsg, []int{3} }

func (m *RPCMethodReturn) GetCallSeq() uint32 {
	if m != nil {
		return m.CallSeq
	}
	return 0
}

func (m *RPCMethodReturn) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RPCMethodReturn) GetReturns() map[string]*RPCValue {
	if m != nil {
		return m.Returns
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCValue)(nil), "rpc.RPCValue")
	proto.RegisterType((*RPCHandShake)(nil), "rpc.RPCHandShake")
	proto.RegisterType((*RPCMethodCall)(nil), "rpc.RPCMethodCall")
	proto.RegisterType((*RPCMethodReturn)(nil), "rpc.RPCMethodReturn")
	proto.RegisterEnum("rpc.RPC_MSGID", RPC_MSGID_name, RPC_MSGID_value)
}
func (m *RPCValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RPCValue) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(m.Kind))
	dAtA[i] = 0x10
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(m.I32))
	dAtA[i] = 0x18
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(m.I64))
	dAtA[i] = 0x20
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(m.U32))
	dAtA[i] = 0x28
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(m.U64))
	dAtA[i] = 0x35
	i++
	i = encodeFixed32RpcMsg(dAtA, i, uint32(math.Float32bits(float32(m.F32))))
	dAtA[i] = 0x39
	i++
	i = encodeFixed64RpcMsg(dAtA, i, uint64(math.Float64bits(float64(m.F64))))
	dAtA[i] = 0x40
	i++
	if m.B {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x4a
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(len(m.S)))
	i += copy(dAtA[i:], m.S)
	if len(m.I32A) > 0 {
		for _, num := range m.I32A {
			dAtA[i] = 0x50
			i++
			i = encodeVarintRpcMsg(dAtA, i, uint64(num))
		}
	}
	if len(m.I64A) > 0 {
		for _, num := range m.I64A {
			dAtA[i] = 0x58
			i++
			i = encodeVarintRpcMsg(dAtA, i, uint64(num))
		}
	}
	if len(m.U32A) > 0 {
		for _, num := range m.U32A {
			dAtA[i] = 0x60
			i++
			i = encodeVarintRpcMsg(dAtA, i, uint64(num))
		}
	}
	if len(m.U64A) > 0 {
		for _, num := range m.U64A {
			dAtA[i] = 0x68
			i++
			i = encodeVarintRpcMsg(dAtA, i, uint64(num))
		}
	}
	if len(m.F32A) > 0 {
		for _, num := range m.F32A {
			dAtA[i] = 0x75
			i++
			f1 := math.Float32bits(float32(num))
			dAtA[i] = uint8(f1)
			i++
			dAtA[i] = uint8(f1 >> 8)
			i++
			dAtA[i] = uint8(f1 >> 16)
			i++
			dAtA[i] = uint8(f1 >> 24)
			i++
		}
	}
	if len(m.F64A) > 0 {
		for _, num := range m.F64A {
			dAtA[i] = 0x79
			i++
			f2 := math.Float64bits(float64(num))
			dAtA[i] = uint8(f2)
			i++
			dAtA[i] = uint8(f2 >> 8)
			i++
			dAtA[i] = uint8(f2 >> 16)
			i++
			dAtA[i] = uint8(f2 >> 24)
			i++
			dAtA[i] = uint8(f2 >> 32)
			i++
			dAtA[i] = uint8(f2 >> 40)
			i++
			dAtA[i] = uint8(f2 >> 48)
			i++
			dAtA[i] = uint8(f2 >> 56)
			i++
		}
	}
	if len(m.Ba) > 0 {
		for _, b := range m.Ba {
			dAtA[i] = 0x80
			i++
			dAtA[i] = 0x1
			i++
			if b {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i++
		}
	}
	if len(m.Sa) > 0 {
		for _, s := range m.Sa {
			dAtA[i] = 0x8a
			i++
			dAtA[i] = 0x1
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *RPCHandShake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RPCHandShake) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(len(m.EndName)))
	i += copy(dAtA[i:], m.EndName)
	dAtA[i] = 0x12
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(len(m.EndModelName)))
	i += copy(dAtA[i:], m.EndModelName)
	return i, nil
}

func (m *RPCMethodCall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RPCMethodCall) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(m.CallSeq))
	dAtA[i] = 0x12
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(len(m.Method)))
	i += copy(dAtA[i:], m.Method)
	if len(m.Args) > 0 {
		for k, _ := range m.Args {
			dAtA[i] = 0x1a
			i++
			v := m.Args[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovRpcMsg(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovRpcMsg(uint64(len(k))) + msgSize
			i = encodeVarintRpcMsg(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintRpcMsg(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintRpcMsg(dAtA, i, uint64(v.Size()))
				n3, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n3
			}
		}
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(len(m.Caller)))
	i += copy(dAtA[i:], m.Caller)
	return i, nil
}

func (m *RPCMethodReturn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RPCMethodReturn) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(m.CallSeq))
	dAtA[i] = 0x12
	i++
	i = encodeVarintRpcMsg(dAtA, i, uint64(len(m.Method)))
	i += copy(dAtA[i:], m.Method)
	if len(m.Returns) > 0 {
		for k, _ := range m.Returns {
			dAtA[i] = 0x1a
			i++
			v := m.Returns[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovRpcMsg(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovRpcMsg(uint64(len(k))) + msgSize
			i = encodeVarintRpcMsg(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintRpcMsg(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintRpcMsg(dAtA, i, uint64(v.Size()))
				n4, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n4
			}
		}
	}
	return i, nil
}

func encodeFixed64RpcMsg(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32RpcMsg(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintRpcMsg(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RPCValue) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovRpcMsg(uint64(m.Kind))
	n += 1 + sovRpcMsg(uint64(m.I32))
	n += 1 + sovRpcMsg(uint64(m.I64))
	n += 1 + sovRpcMsg(uint64(m.U32))
	n += 1 + sovRpcMsg(uint64(m.U64))
	n += 5
	n += 9
	n += 2
	l = len(m.S)
	n += 1 + l + sovRpcMsg(uint64(l))
	if len(m.I32A) > 0 {
		for _, e := range m.I32A {
			n += 1 + sovRpcMsg(uint64(e))
		}
	}
	if len(m.I64A) > 0 {
		for _, e := range m.I64A {
			n += 1 + sovRpcMsg(uint64(e))
		}
	}
	if len(m.U32A) > 0 {
		for _, e := range m.U32A {
			n += 1 + sovRpcMsg(uint64(e))
		}
	}
	if len(m.U64A) > 0 {
		for _, e := range m.U64A {
			n += 1 + sovRpcMsg(uint64(e))
		}
	}
	if len(m.F32A) > 0 {
		n += 5 * len(m.F32A)
	}
	if len(m.F64A) > 0 {
		n += 9 * len(m.F64A)
	}
	if len(m.Ba) > 0 {
		n += 3 * len(m.Ba)
	}
	if len(m.Sa) > 0 {
		for _, s := range m.Sa {
			l = len(s)
			n += 2 + l + sovRpcMsg(uint64(l))
		}
	}
	return n
}

func (m *RPCHandShake) Size() (n int) {
	var l int
	_ = l
	l = len(m.EndName)
	n += 1 + l + sovRpcMsg(uint64(l))
	l = len(m.EndModelName)
	n += 1 + l + sovRpcMsg(uint64(l))
	return n
}

func (m *RPCMethodCall) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovRpcMsg(uint64(m.CallSeq))
	l = len(m.Method)
	n += 1 + l + sovRpcMsg(uint64(l))
	if len(m.Args) > 0 {
		for k, v := range m.Args {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovRpcMsg(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovRpcMsg(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovRpcMsg(uint64(mapEntrySize))
		}
	}
	l = len(m.Caller)
	n += 1 + l + sovRpcMsg(uint64(l))
	return n
}

func (m *RPCMethodReturn) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovRpcMsg(uint64(m.CallSeq))
	l = len(m.Method)
	n += 1 + l + sovRpcMsg(uint64(l))
	if len(m.Returns) > 0 {
		for k, v := range m.Returns {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovRpcMsg(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovRpcMsg(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovRpcMsg(uint64(mapEntrySize))
		}
	}
	return n
}

func sovRpcMsg(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozRpcMsg(x uint64) (n int) {
	return sovRpcMsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RPCValue) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpcMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RPCValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RPCValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field I32", wireType)
			}
			m.I32 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.I32 |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field I64", wireType)
			}
			m.I64 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.I64 |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field U32", wireType)
			}
			m.U32 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.U32 |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field U64", wireType)
			}
			m.U64 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.U64 |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000010)
		case 6:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field F32", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.F32 = float32(math.Float32frombits(v))
			hasFields[0] |= uint64(0x00000020)
		case 7:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field F64", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.F64 = float64(math.Float64frombits(v))
			hasFields[0] |= uint64(0x00000040)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field B", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.B = bool(v != 0)
			hasFields[0] |= uint64(0x00000080)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field S", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.S = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000100)
		case 10:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.I32A = append(m.I32A, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRpcMsg
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.I32A = append(m.I32A, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field I32A", wireType)
			}
		case 11:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.I64A = append(m.I64A, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRpcMsg
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.I64A = append(m.I64A, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field I64A", wireType)
			}
		case 12:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.U32A = append(m.U32A, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRpcMsg
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.U32A = append(m.U32A, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field U32A", wireType)
			}
		case 13:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.U64A = append(m.U64A, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRpcMsg
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.U64A = append(m.U64A, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field U64A", wireType)
			}
		case 14:
			if wireType == 5 {
				var v uint32
				if (iNdEx + 4) > l {
					return io.ErrUnexpectedEOF
				}
				iNdEx += 4
				v = uint32(dAtA[iNdEx-4])
				v |= uint32(dAtA[iNdEx-3]) << 8
				v |= uint32(dAtA[iNdEx-2]) << 16
				v |= uint32(dAtA[iNdEx-1]) << 24
				v2 := float32(math.Float32frombits(v))
				m.F32A = append(m.F32A, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint32
					if (iNdEx + 4) > l {
						return io.ErrUnexpectedEOF
					}
					iNdEx += 4
					v = uint32(dAtA[iNdEx-4])
					v |= uint32(dAtA[iNdEx-3]) << 8
					v |= uint32(dAtA[iNdEx-2]) << 16
					v |= uint32(dAtA[iNdEx-1]) << 24
					v2 := float32(math.Float32frombits(v))
					m.F32A = append(m.F32A, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field F32A", wireType)
			}
		case 15:
			if wireType == 1 {
				var v uint64
				if (iNdEx + 8) > l {
					return io.ErrUnexpectedEOF
				}
				iNdEx += 8
				v = uint64(dAtA[iNdEx-8])
				v |= uint64(dAtA[iNdEx-7]) << 8
				v |= uint64(dAtA[iNdEx-6]) << 16
				v |= uint64(dAtA[iNdEx-5]) << 24
				v |= uint64(dAtA[iNdEx-4]) << 32
				v |= uint64(dAtA[iNdEx-3]) << 40
				v |= uint64(dAtA[iNdEx-2]) << 48
				v |= uint64(dAtA[iNdEx-1]) << 56
				v2 := float64(math.Float64frombits(v))
				m.F64A = append(m.F64A, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					iNdEx += 8
					v = uint64(dAtA[iNdEx-8])
					v |= uint64(dAtA[iNdEx-7]) << 8
					v |= uint64(dAtA[iNdEx-6]) << 16
					v |= uint64(dAtA[iNdEx-5]) << 24
					v |= uint64(dAtA[iNdEx-4]) << 32
					v |= uint64(dAtA[iNdEx-3]) << 40
					v |= uint64(dAtA[iNdEx-2]) << 48
					v |= uint64(dAtA[iNdEx-1]) << 56
					v2 := float64(math.Float64frombits(v))
					m.F64A = append(m.F64A, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field F64A", wireType)
			}
		case 16:
			if wireType == 0 {
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Ba = append(m.Ba, bool(v != 0))
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRpcMsg
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Ba = append(m.Ba, bool(v != 0))
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Ba", wireType)
			}
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sa", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sa = append(m.Sa, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpcMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpcMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("kind")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("i32")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("i64")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("u32")
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("u64")
	}
	if hasFields[0]&uint64(0x00000020) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("f32")
	}
	if hasFields[0]&uint64(0x00000040) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("f64")
	}
	if hasFields[0]&uint64(0x00000080) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("b")
	}
	if hasFields[0]&uint64(0x00000100) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("s")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RPCHandShake) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpcMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RPCHandShake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RPCHandShake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndModelName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndModelName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipRpcMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpcMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("endName")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("endModelName")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RPCMethodCall) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpcMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RPCMethodCall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RPCMethodCall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallSeq", wireType)
			}
			m.CallSeq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CallSeq |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(dAtA[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			if m.Args == nil {
				m.Args = make(map[string]*RPCValue)
			}
			if iNdEx < postIndex {
				var valuekey uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					valuekey |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				var mapmsglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					mapmsglen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if mapmsglen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				postmsgIndex := iNdEx + mapmsglen
				if mapmsglen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				if postmsgIndex > l {
					return io.ErrUnexpectedEOF
				}
				mapvalue := &RPCValue{}
				if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
					return err
				}
				iNdEx = postmsgIndex
				m.Args[mapkey] = mapvalue
			} else {
				var mapvalue *RPCValue
				m.Args[mapkey] = mapvalue
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Caller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Caller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipRpcMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpcMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("call_seq")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("method")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("caller")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RPCMethodReturn) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpcMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RPCMethodReturn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RPCMethodReturn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallSeq", wireType)
			}
			m.CallSeq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CallSeq |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Returns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthRpcMsg
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(dAtA[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			if m.Returns == nil {
				m.Returns = make(map[string]*RPCValue)
			}
			if iNdEx < postIndex {
				var valuekey uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					valuekey |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				var mapmsglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					mapmsglen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if mapmsglen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				postmsgIndex := iNdEx + mapmsglen
				if mapmsglen < 0 {
					return ErrInvalidLengthRpcMsg
				}
				if postmsgIndex > l {
					return io.ErrUnexpectedEOF
				}
				mapvalue := &RPCValue{}
				if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
					return err
				}
				iNdEx = postmsgIndex
				m.Returns[mapkey] = mapvalue
			} else {
				var mapvalue *RPCValue
				m.Returns[mapkey] = mapvalue
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpcMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpcMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("call_seq")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("method")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRpcMsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRpcMsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRpcMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthRpcMsg
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRpcMsg
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRpcMsg(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRpcMsg = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRpcMsg   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("rpc_msg.proto", fileDescriptorRpcMsg) }

var fileDescriptorRpcMsg = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x4f, 0xdb, 0x30,
	0x18, 0x87, 0xb1, 0x9d, 0xd2, 0xf6, 0xa5, 0x85, 0xe2, 0x49, 0xc8, 0x42, 0xa8, 0x78, 0xdd, 0xc5,
	0xda, 0xa1, 0x9a, 0xda, 0x28, 0x9a, 0xb6, 0x53, 0x09, 0x68, 0x4c, 0xfc, 0x59, 0xe5, 0x6e, 0xd3,
	0x6e, 0xc8, 0x6d, 0x5c, 0x40, 0x84, 0xb4, 0x24, 0xcd, 0x24, 0x6e, 0x7c, 0x84, 0x7d, 0x2c, 0x8e,
	0xfb, 0x04, 0x68, 0x62, 0xd7, 0x1d, 0x77, 0xdb, 0xc4, 0x26, 0x3b, 0x24, 0x6a, 0xcf, 0xf4, 0xd2,
	0x37, 0xcf, 0xfb, 0xf8, 0x75, 0x7e, 0xb1, 0xa1, 0x1e, 0x4f, 0x47, 0x27, 0x97, 0xc9, 0x69, 0x7b,
	0x1a, 0x4f, 0x66, 0x13, 0x4a, 0xe2, 0xe9, 0xa8, 0xf5, 0x1b, 0x43, 0x45, 0xf6, 0xfd, 0xcf, 0x2a,
	0x4c, 0x35, 0x65, 0xe0, 0x5c, 0x9c, 0x47, 0x01, 0x43, 0x1c, 0x8b, 0xd2, 0x8e, 0x73, 0x7b, 0xb7,
	0xbd, 0x24, 0x2d, 0xa1, 0x1b, 0x40, 0xce, 0xbb, 0x1d, 0x86, 0xe7, 0x1a, 0x06, 0x58, 0xee, 0xb9,
	0x8c, 0x70, 0x2c, 0x48, 0xc1, 0x3d, 0xd7, 0xf0, 0xb4, 0xdb, 0x61, 0x0e, 0xc7, 0xa2, 0x9e, 0xf3,
	0x34, 0xf3, 0x53, 0xcf, 0x65, 0x25, 0x8e, 0x85, 0x53, 0xf0, 0xcc, 0x1f, 0x77, 0x3b, 0x6c, 0x99,
	0x63, 0x81, 0x73, 0x3e, 0xce, 0xfc, 0xb1, 0xe7, 0xb2, 0x32, 0xc7, 0x02, 0x15, 0xdc, 0x73, 0x29,
	0x05, 0x34, 0x64, 0x15, 0x8e, 0x45, 0xe5, 0x91, 0xa2, 0xa1, 0x61, 0x09, 0xab, 0x72, 0x2c, 0xaa,
	0x39, 0x4b, 0x28, 0x05, 0xe7, 0xbc, 0xdb, 0x51, 0x0c, 0x38, 0x11, 0x25, 0x69, 0x6b, 0xcb, 0x3c,
	0x57, 0xb1, 0x15, 0x4e, 0x04, 0x91, 0xb6, 0x36, 0x2c, 0x35, 0x5e, 0x8d, 0x13, 0x51, 0x97, 0xb6,
	0xb6, 0xcc, 0x78, 0x75, 0x4e, 0x84, 0x23, 0x6d, 0x6d, 0xd8, 0xd8, 0x78, 0xab, 0x9c, 0x08, 0x2c,
	0x6d, 0x6d, 0x99, 0xf1, 0xd6, 0x38, 0x11, 0x48, 0xda, 0x9a, 0xae, 0x02, 0x1e, 0x2a, 0xd6, 0xe0,
	0x44, 0x54, 0x24, 0x1e, 0xda, 0xe7, 0x44, 0xb1, 0x75, 0x4e, 0x44, 0x55, 0xe2, 0x44, 0xb5, 0xbe,
	0x40, 0x4d, 0xf6, 0xfd, 0x7d, 0x15, 0x05, 0x83, 0x33, 0x75, 0xa1, 0x69, 0x13, 0xca, 0x3a, 0x0a,
	0x8e, 0xd5, 0xa5, 0xb6, 0x1f, 0x3f, 0x4f, 0x90, 0x43, 0x2a, 0xa0, 0xa6, 0xa3, 0xe0, 0x68, 0x12,
	0xe8, 0xd0, 0x4a, 0x78, 0x4e, 0x5a, 0xe8, 0xb4, 0x7e, 0x21, 0xa8, 0xcb, 0xbe, 0x7f, 0xa4, 0x67,
	0x67, 0x93, 0xc0, 0x57, 0x61, 0x48, 0xb7, 0xa1, 0x32, 0x52, 0x61, 0x78, 0x92, 0xe8, 0x2b, 0x3b,
	0x3c, 0x3f, 0x90, 0xb2, 0xa1, 0x03, 0x7d, 0x45, 0xb7, 0x60, 0xf9, 0xd2, 0xea, 0x0b, 0x63, 0x1f,
	0x19, 0x7d, 0x05, 0x8e, 0x8a, 0x4f, 0x13, 0x46, 0x38, 0x11, 0x2b, 0x9d, 0xad, 0x76, 0x3c, 0x1d,
	0xb5, 0x17, 0x36, 0x68, 0xf7, 0xe2, 0xd3, 0x64, 0x2f, 0x9a, 0xc5, 0xd7, 0xd2, 0x9a, 0x66, 0x9e,
	0x19, 0xad, 0x63, 0x7b, 0xfe, 0xc5, 0xbc, 0x8c, 0x6d, 0x1e, 0x42, 0xb5, 0x58, 0x60, 0xce, 0xf7,
	0x42, 0x5f, 0x33, 0xc4, 0x51, 0xe1, 0x19, 0x40, 0x5f, 0x40, 0xe9, 0xab, 0xb9, 0x92, 0x0c, 0x73,
	0x24, 0x56, 0x3a, 0xf5, 0x7c, 0x57, 0x7b, 0x4f, 0x65, 0xd6, 0x7b, 0x83, 0x5f, 0xa3, 0xd6, 0x1d,
	0x82, 0xb5, 0xe2, 0x6d, 0xa4, 0x9e, 0xa5, 0x71, 0xf4, 0xd4, 0xc0, 0x6f, 0xa1, 0x1c, 0xdb, 0x41,
	0x79, 0xe6, 0xe7, 0x8b, 0x99, 0xb3, 0x5d, 0xda, 0xd9, 0xdf, 0x63, 0xf0, 0x7c, 0xc5, 0xe6, 0x07,
	0xa8, 0xcd, 0x37, 0x9e, 0x1c, 0xf0, 0xe5, 0x01, 0x54, 0x65, 0xdf, 0x3f, 0x39, 0x1a, 0xbc, 0x7b,
	0xbf, 0x4b, 0x37, 0xa0, 0xba, 0xdf, 0x3b, 0xde, 0x1d, 0xec, 0xf7, 0x0e, 0xf6, 0x1a, 0x37, 0x0f,
	0xff, 0xb2, 0x1f, 0xa2, 0xeb, 0xe0, 0xf8, 0xbd, 0xc3, 0xc3, 0xc6, 0xcd, 0xdf, 0x02, 0x3d, 0x83,
	0x65, 0xb9, 0xf7, 0xf1, 0x93, 0x3c, 0x6e, 0x3c, 0xfc, 0xc9, 0xe1, 0x4e, 0xe3, 0xf6, 0xbe, 0x89,
	0xbe, 0xdf, 0x37, 0xd1, 0x8f, 0xfb, 0x26, 0xfa, 0xf6, 0xb3, 0xb9, 0xf4, 0x3f, 0x00, 0x00, 0xff,
	0xff, 0x5a, 0xc0, 0x6d, 0x8b, 0x14, 0x04, 0x00, 0x00,
}
